### ISSUE TITLE
panic: exit status 1

### ISSUE THREAD

**Issue by hoppalazi** [rdalbuquerque/azdoext#4]
Hey,
after installation i can successfully run `azdoext -version` with output `v0.0.1`.
But running just `azdoext` after setting the environment variable AZDO_PERSONAL_ACCESS_TOKEN leads to following error stack:
```
panic: exit status 1

goroutine 71 [running]:
azdoext/pkgs/gitexec.Config()
/home/runner/work/azdoext/azdoext/pkgs/gitexec/gitexec.go:32 +0x198
main.(*model).Init.getAzdoConfig.func1()
/home/runner/work/azdoext/azdoext/main.go:68 +0x25
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:294 +0x29
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1 in goroutine 69
/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:293 +0x139
```

**Comment by rdalbuquerque** [comment]
Hi, are you running from an initiated git repo with an azure devops remote origin?
If not, please do so, I still need better error handling for that.

**Comment by hoppalazi** [comment]
No, i was just in my user directory. I somehow missed that i have to be in a Azure DevOps repository.

**Comment by rdalbuquerque** [comment]
I've also added better error handling in 20a13722eb08dad0facdd6b5f017f8d6df6bb0c5

**Comment by hoppalazi** [comment]
If you're fine with that, i'd close this isse since the original issue is resolved and open another issue regarding the missing pipelines.

**Comment by rdalbuquerque** [comment]
Sure, we can do that
